# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'acade_development' %>
  username: <%= ENV['DB_USERNAME'] || 'postgres' %>
  password: <%= ENV['DB_PASSWORD'] || 'postgres123' %>
  host: <%= ENV['DB_HOST'] || '127.0.0.1' %>
  port: <%= ENV['DB_PORT'] || 5432 %>

test:
  <<: *default
  database: <%= ENV['DB_NAME_TEST'] || 'acade_test' %>
  username: <%= ENV['DB_USERNAME'] || 'postgres' %>
  password: <%= ENV['DB_PASSWORD'] || 'postgres123' %>
  host: <%= ENV['DB_HOST'] || '127.0.0.1' %>
  port: <%= ENV['DB_PORT'] || 5432 %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL_PRODUCTION'] %>

queue:
  <<: *default
  url: <%= ENV['DATABASE_URL_PRODUCTION'] %>

cache:
  <<: *default
  url: <%= ENV['DATABASE_URL_PRODUCTION'] %>
  
cable:
  production:
    <<: *default
    url: <%= ENV['DATABASE_URL_PRODUCTION'] %>
